project_id = "mybaipaiuffwvizcqzlc"

[functions.horus-behavior]
verify_jwt = false

[functions.horus-chart-image]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false
